[package]
name = "portugol_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.32"
anyhow = "1.0.61"
phf = { version = "0.11", features = ["macros"] }
